import { test, expect, chromium } from '@playwright/test'

test.skip('Test the lecturer settings page (add, delete, etc)', async ({ page }) => {
  const browser = await chromium.launch({ headless: false }) // Launch the browser in non-headless mode
  const context = await browser.newContext()
  page = await context.newPage()
  await page.goto('https://consultation-scheduler.azurewebsites.net/')
  await page.getByLabel('Username or email address').click()
  await page.getByLabel('Username or email address').fill('test2@wits.ac.za')
  await page.getByLabel('Password').click()
  await page.getByLabel('Password').fill('Testing1!')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('link', { name: 'Settings' }).click()
  await page.getByRole('heading', { name: 'Specify a consultation period' }).click()
  await page.getByText('Day of the Week').click()
  await page.getByRole('combobox', { name: 'Day of the Week' }).selectOption('Friday')
  await page.getByText('Document Hi test2 Dashboard Settings Logout Specify a consultation period Day of').click()
  await page.getByText('Document Hi test2 Dashboard Settings Logout Specify a consultation period Day of').click()
  await page.getByRole('heading', { name: 'Consultation settings' }).click()
  await page.getByText('Specify the max number of students per consultation').click()
  await page.getByLabel('Specify the max number of students per consultation').click()
  await page.getByLabel('Specify the max number of students per consultation').click()
  await page.getByLabel('Specify the max number of students per consultation').click()
  await page.getByLabel('Specify the max number of students per consultation').fill('5')
  await page.getByText('Specify the max number of consulatations per period/day').click()
  await page.locator('input[name="maxConsultations"]').click()
  await page.locator('input[name="maxConsultations"]').fill('3')
  await page.getByRole('combobox', { name: 'Select duration of a consultation (in minutes):' }).selectOption('30')
  await page.getByRole('button', { name: 'Submit' }).click()
  await page.getByText('1. Friday - NaN:undefined to NaN:undefined where 3 consultations of 30 minutes can be booked with a max of 5 students per consultation').click()
  await page.getByRole('combobox', { name: 'Day of the Week' }).selectOption('Wednesday')
  await page.getByRole('button', { name: 'Submit' }).click()
  await page.getByRole('listitem').filter({ hasText: '2. Wednesday - NaN:undefined to NaN:undefined where 3 consultations of 30 minutes can be booked with a max of 5 students per consultation' }).getByRole('button', { name: 'Delete' }).click()
  await page.getByText('1. Friday - NaN:undefined to NaN:undefined where 3 consultations of 30 minutes can be booked with a max of 5 students per consultation').click()
})